### ISSUE TITLE
assertThat should take vararg criteria

### ISSUE THREAD

**Issue by dalewking** [npryce/hamkrest#10]
While doing some checks on the same item that requires checking multiple things it occurred to me that this function:

```
fun <T> assertThat(actual: T, criteria: Matcher<T>) {
    _assertThat(null, actual, criteria)
}
```

could be more convenient as:

```
fun <T> assertThat(actual: T, vararg criteria: Matcher<T>) {
    criteria.foreach {_assertThat(null, actual, it) }
}
```

**Comment by npryce** [comment]
I prefer not to, because varargs makes it implicit that you are asserting the logical conjunction of all the matchers.  At the moment, you can get what you want by using the `and` prefix function, which only uses a few more keystrokes and explicity communicates the matching criteria.

E.g. `assertThat('ohio', roundAtTheEnds() and highInTheMiddle())`

**Comment by dalewking** [comment]
Note that what I suggested was different than and, which is why I suggested it. "And" would be one assertion that when failed would contain the text of all the matchers linked together with and. What I proposed was mulitple assertThat statements each containing only one matcher so when it fails you see only the description of the matcher that failed, which can help in tracing down what failed. And certainly has its place, but sometimes it is more convenient to do a bunch of individual assertions

Of course, the beauty of Kotlin is that if you don't add it I can declare it myself

**Comment by rocketraman** [comment]
> sometimes it is more convenient to do a bunch of individual assertions

@dalewking  For this, I like to use the following idiom which IMO is clearer than providing the arguments as varargs because the line number takes you directly to the failing assertion:

```
doSomething().let {
  assertThat(it, ...)
  assertThat(it, ...)
  assertThat(it, ...)
}
```

**Comment by dalewking** [comment]
That definitely is more Kotlin-esque.
