### ISSUE TITLE
Change the description of assertion errors so that IntelliJ shows the "show difference" option in the console output.

### ISSUE THREAD

**Issue by DenEwout** [npryce/hamkrest#12]
Hello,

Love using hamkrest! but I have one gripe with it. IntelliJ doesn't show the "show difference" option when an assertion fails. This is quite handy when you're asserting the contents of data classes.

A quick google shows that IntelliJ offers this functionality simply by checking a regular expression. Would it be possible to change the description strings so that IntelliJ shows the "show difference" option when using hamkrest?

Kind regards,

Ewout.

**Comment by DenEwout** [comment]
Hi,

I haven't seen any activity on this issue, will this be considered later?

Kind regards,

Ewout.

**Comment by AndreasVolkmann** [comment]
Hi,

I just checked it out. 

Adding support for the show difference option is really as easy as editing a few String values. 

I have a branch where the functionality is implemented. 

![image](https://cloud.githubusercontent.com/assets/9032394/18227260/8574655a-721e-11e6-8d34-a07f0e6cda8b.png)

**Comment by DenEwout** [comment]
Would you mind creating a pull request for it? (or sharing your fork?)

**Comment by AndreasVolkmann** [comment]
I think I need special permissions to create a pull request (idk).

Here is my fork: 
[https://github.com/goreRatzete/hamkrest](https://github.com/goreRatzete/hamkrest)

**Comment by DenEwout** [comment]
You don't need special permissions, I took the liberty and did it for you. (see: https://github.com/npryce/hamkrest/pull/13)

You can just go to your fork on github, and click create pull request. For a more complete guide you can check: https://help.github.com/articles/creating-a-pull-request/

Thanks for helping me out!

**Comment by npryce** [comment]
PR merged

**Comment by corbym** [comment]
This seems to break for very long strings (or very long lists).. but perhaps isn't this code's fault. Not sure as it might be the IDE's problem.
