### ISSUE TITLE
equalTo() support for kotlin Sequences

### ISSUE THREAD

**Issue by dkandalov** [npryce/hamkrest#17]
E.g. the following assertion currently fails:

``` kotlin
assertThat(sequenceOf(1, 2, 3), equalTo(sequenceOf(1, 2, 3)))
```

**Comment by npryce** [comment]
Kotlin Sequences are not values, so equality doesn't really make sense for sequences.  In this case, I would do `assertThat(seqA.toList(), equalTo(seqB.toList())`.

or even... `assertThat(seqA, has(Sequence::toList, equalTo(listOf(1,2,3)))`

In general, I find that working type inference, `has` function, and function/method references let you do a lot things that in Java Hamcrest required ad-hoc behaviour or additional matchers.

**Comment by dkandalov** [comment]
Yes, `.toList()` works fine.

After thinking about it a bit more, I agree this is a bad feature request.
In general, it's not clear whether to consume `Sequence`s into lists to compare them or use `equals` method on `Sequence` objects which might or might not compare content of sequences. So from library point of view it makes perfect sense to use equality method on objects.

It should've been a Kotlin issue to make `sequenceOf(1, 2, 3)` produce sequences with equality (e.g. https://youtrack.jetbrains.com/issue/KT-8511).
