### ISSUE TITLE
Add assertThat overload with the reason argument as Function0<String>

### ISSUE THREAD

**Issue by sedovalx** [npryce/hamkrest#18]
Sometimes it is useful not to evaluate the reason expression until the assertion failed. Example:

    val userJson = JsonPath.parse(userResponseBody)
    assertThat(
        userJson.read("$.error_description"), 
        userResponse.status, 
        equalTo(Response.Status.OK.statusCode)
    )

Possible solution would be

    fun <T> assertThat(actual: T, matcher: Matcher<in T>, reason: () -> String) {
        if (!matcher.matches(actual)) {
            val description = StringDescription()
            description.appendText(reason.invoke())
                    .appendText("\nExpected: ")
                    .appendDescriptionOf(matcher)
                    .appendText("\n     but: ")
            matcher.describeMismatch(actual, description)

            throw AssertionError(description.toString())
        }
    }

    fun <T> assertThat(reason: String, actual: T, matcher: Matcher<in T>) = 
        assertThat(actual, matcher) { reason }

**Comment by npryce** [comment]
This is a good idea.   I'll have a think about how to do this without too much duplication.

**Comment by npryce** [comment]
In version 1.4.0.0
