### ISSUE TITLE
Add more sugar

### ISSUE THREAD

**Issue by FaustXVI** [npryce/hamkrest#19]
What about adding more syntactic sugar to have assertions that reads even better like : 
```kotlin
"banana" should starts with "bana"
```
Kotlintest has something similar so I know it's doable :)
I'll be happy to PR this if interested.

**Comment by npryce** [comment]
There is already an extension function shouldMatch.  E.g. `banana.shouldMatch(startsWith("bana")`

HamKrest will never have an API that splits things up into words to try and mimic English.  That kind of design leads to huge amounts of duplicated logic and APIs that are very hard to explore and find the required sequence of calls for a specific need.

The goal of Hamcrest and HamKrest is to form a readable _notation_, not English clauses.

A happy effect of its design is that duplicate logic is avoided.

**Comment by FaustXVI** [comment]
Fair enough ! Thanks for the reply :)
