### ISSUE TITLE
Upgrade to Kotlin 1.1

### ISSUE THREAD

**Issue by npryce** [npryce/hamkrest#23]
Kotlin 1.1 has moved reflection classes into a new package, and deprecated the ones in the kotlin.reflect package

**Comment by arturbosch** [comment]
The String.toInt() method now has an overloaded version `String.toInt(radix: Int)` and is ambigious, which leds to compilation errors eg. `assertThat("1234", !has(String::toInt, equalTo(12345)))`.

Also using hamkrest with 1.1 will crash all tests with following error message: 
```
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Reflection on built-in Kotlin types is not yet fully supported. No metadata found for public abstract val size: kotlin.Int defined in kotlin.collections.Collection[DeserializedPropertyDescriptor@56102e1c]
```

**Comment by VerachadW** [comment]
What is the progress of this issue? Are you working on this one? @npryce

**Comment by npryce** [comment]
PR merged

**Comment by npryce** [comment]
In version 1.4.0.0
