### ISSUE TITLE
Available via Gradle?

### ISSUE THREAD

**Issue by davidgoli** [npryce/hamkrest#33]
Hi, I'm trying to install by adding to my app's build.gradle:

`testCompile 'com.natpryce.hamkrest:1.4.2.0'`

but wasn't in your README, and it fails to resolve, and I found that this plugin is missing on plugins.gradle.org. I haven't authored a plugin myself but I believe this just requires publishing to plugins.gradle.org. That would make this library infinitely more useful. Thanks!

**Comment by alexandru-calinoiu** [comment]
Apparently you can grab it via [maven central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22hamkrest%22)

**Comment by npryce** [comment]
It's not a gradle plugin.   It's merely a Kotlin library.

Click on the maven central badge in the readme, and it will take you to a page that shows how to add the library to Gradle.

http://search.maven.org/#artifactdetails%7Ccom.natpryce%7Chamkrest%7C1.4.2.0%7Cjar
