### ISSUE TITLE
IntelliJ doesn't always show source

### ISSUE THREAD

**Issue by dmcg** [npryce/hamkrest#36]
In IntelliJ, opening the 'External Libraries' view and finding Hamkrest, some of the 'files' are listed with a .class extension (CollectionMatchers.class) and some are not (CaseSensitity). The source for the latter is shown, the former just shows a decompiled version.

It applies Maven and Gradle projects imported into IntelliJ, and certainly hampers my ability to work out how to use the library.

**Comment by dmcg** [comment]
Looking deeper, we are only shown the source for classes. Files containing top-level functions are not showing source (unless they happen to contain a class, but then you still navigate into a non-source view)

**Comment by dmcg** [comment]
I've also logged https://youtrack.jetbrains.com/issue/IDEA-180827

**Comment by npryce** [comment]
Closing because it's not something Hamkrest can solve
