### ISSUE TITLE
`assert` object is unable to be automatically imported by Intellij

### ISSUE THREAD

**Issue by magneticflux-** [npryce/hamkrest#39]
Probably because it's a Kotlin function as well. It's just a minor annoyance that I've been having. Does anyone have workarounds or alternatives that I don't know about? Using `assertThat` instead of `assert.that` works fine.

**Comment by npryce** [comment]
Sounds like an issue with IntelliJ's autoimport, not Hamkrest itself.

**Comment by volkert-fastned** [comment]
@npryce @npryce-springer It might be helpful to clarify in the README that as of version 1.7.0.0, "assert.that" has been changed back to "assertThat" after all. This is a breaking API change that needs some refactoring, albeit trivial. Also, I'm curious: why is 1.7.0.0 not yet tagged as a release in this GitHub repo, even though it has already been published in Maven Central? Thanks.
