### ISSUE TITLE
Support Intellij IDEA's automatic diff calculation

### ISSUE THREAD

**Issue by magneticflux-** [npryce/hamkrest#41]
IDEA can format test errors as diffs between expected and actual, which is helpful for large string/object graph comparisons. It appears that all you would need to do is remove the newline between `expected:` and `but was:`.

Details here: [link](https://stackoverflow.com/questions/10934743/formatting-output-so-that-intellij-idea-shows-diffs-for-two-texts)

Modern reference to the location in IDEA source: [link](https://github.com/JetBrains/intellij-community/blob/173.4301/plugins/gradle/src/org/jetbrains/plugins/gradle/execution/test/runner/events/AfterTestEvent.java#L76)

**Comment by npryce** [comment]
Implemented
