### ISSUE TITLE
What is the status of Hamkrest?

### ISSUE THREAD

**Issue by chrisr3** [npryce/hamkrest#54]
Hi,

I stumbled across Hamkrest only recently, as I'd been incorrectly assuming that [these](https://github.com/hamcrest) were the only implementations of Hamcrest matchers. And I also see that Hamkrest has existed now for almost 3 years, which would seem to suggest that there are no plans to move it under the [Hamcrest](https://github.com/hamcrest) umbrella either.

Can you tell me what Hamkrest's roadmap is please? I can't help but think of the Yammer/CodaHale/DropWizard metrics library here and wonder if the Hamkrest artifacts could ever mutate in such a way.

Thanks,
Chris

**Comment by npryce** [comment]
I don't know what you're referring to by "Yammer/CodaHale/DropWizard metrics library".

Hamkrest is used for testing business critical systems in many organisations. We do not plan for it to become a grab-bag of matcher classes.  Instead it provides a stable foundation for teams to build libraries of matchers that meet their own needs.

**Comment by chrisr3** [comment]
> I don't know what you're referring to by "Yammer/CodaHale/DropWizard metrics library".

It is a metrics library that started life with Maven coordinate

    group = com.yammer.metrics

which then became

    group = com.codahale.metrics

and is now

    group = io.dropwizard.metrics

with all of the accompanying package name changes thrown in. So I'm asking if there any plans to move Hamkrest into the `org.hamcrest` Maven group, please? After all, Hamkrest _does_ appear to be the implementation of Hamcrest matchers for Kotlin.

Are you claiming that moving Hamkrest to `org.hamcrest` would mean that it would then become "a grab-bag of matcher classes"? (Although I really don't see why it would...)

**Comment by npryce** [comment]
I have no plans to change the maven group name and certainly no plans to
change the Kotlin package names.
