### ISSUE TITLE
Why does anything matcher not accept nullable types

### ISSUE THREAD

**Issue by schleifenkauz** [npryce/hamkrest#55]
I was pretty surprised that the anything matcher doesn't allow things like this:
```
val value: Int? = null
value shouldMatch anything
```
Is there any reason for the `anything` Matcher to be of type `Matcher<Any` and not `Matcher<Any?>`?
If not I would be happy to work on a (very small) pull request to fix this issue. 
If there is a reason I'm interested in hearing it.

**Comment by npryce** [comment]
Fixed.
