### ISSUE TITLE
How about a shouldEqual infix method

### ISSUE THREAD

**Issue by dalewking** [npryce/hamkrest#7]
So you can say 

```
value shouldEqual 42
```

instead of 

```
value shouldMatch equalTo(42)
```

Or perhaps it is just another version of shouldMatch and you say

```
value shouldMatch 42
```

**Comment by npryce** [comment]
I'd rather not. The point of Hamcrest is to pass the Matchers in, so you don't have to write tons of overloaded functions. If you can think of a better name than `shouldMatch` do let us know.
