### ISSUE TITLE
You haven't specified a license

### ISSUE THREAD

**Issue by dalewking** [npryce/hamkrest#8]
Trying to do my due diligence and document and credit all libraries I am using including noting the license, but I notice that you haven't actually declared a license in GitHub

**Comment by npryce** [comment]
I've added the Apache 2 License

**Comment by dalewking** [comment]
Don't see any changes. Usually you would add a LICENSE file to the source tree and specify the license in README.md with a link to the license text

**Comment by npryce** [comment]
I see the LICENSE file. Don't know why you cannot. Reopen this issue if you still cannot see it and I will look into it.
